/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedVocabularyRouteImport } from './routes/_authenticated/vocabulary'
import { Route as AuthenticatedLeaderboardRouteImport } from './routes/_authenticated/leaderboard'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAchievementsRouteImport } from './routes/_authenticated/achievements'
import { Route as AuthenticatedVocabularyIndexRouteImport } from './routes/_authenticated/vocabulary.index'
import { Route as AuthenticatedVocabularyFlashcardsRouteImport } from './routes/_authenticated/vocabulary.flashcards'
import { Route as AuthenticatedVocabularyWordIdRouteImport } from './routes/_authenticated/vocabulary.$wordId'
import { Route as AuthenticatedLessonLessonIdRouteImport } from './routes/_authenticated/lesson.$lessonId'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVocabularyRoute = AuthenticatedVocabularyRouteImport.update({
  id: '/vocabulary',
  path: '/vocabulary',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeaderboardRoute =
  AuthenticatedLeaderboardRouteImport.update({
    id: '/leaderboard',
    path: '/leaderboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAchievementsRoute =
  AuthenticatedAchievementsRouteImport.update({
    id: '/achievements',
    path: '/achievements',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVocabularyIndexRoute =
  AuthenticatedVocabularyIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedVocabularyRoute,
  } as any)
const AuthenticatedVocabularyFlashcardsRoute =
  AuthenticatedVocabularyFlashcardsRouteImport.update({
    id: '/flashcards',
    path: '/flashcards',
    getParentRoute: () => AuthenticatedVocabularyRoute,
  } as any)
const AuthenticatedVocabularyWordIdRoute =
  AuthenticatedVocabularyWordIdRouteImport.update({
    id: '/$wordId',
    path: '/$wordId',
    getParentRoute: () => AuthenticatedVocabularyRoute,
  } as any)
const AuthenticatedLessonLessonIdRoute =
  AuthenticatedLessonLessonIdRouteImport.update({
    id: '/lesson/$lessonId',
    path: '/lesson/$lessonId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/learn': typeof LearnRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/achievements': typeof AuthenticatedAchievementsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/vocabulary': typeof AuthenticatedVocabularyRouteWithChildren
  '/lesson/$lessonId': typeof AuthenticatedLessonLessonIdRoute
  '/vocabulary/$wordId': typeof AuthenticatedVocabularyWordIdRoute
  '/vocabulary/flashcards': typeof AuthenticatedVocabularyFlashcardsRoute
  '/vocabulary/': typeof AuthenticatedVocabularyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/learn': typeof LearnRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/achievements': typeof AuthenticatedAchievementsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/lesson/$lessonId': typeof AuthenticatedLessonLessonIdRoute
  '/vocabulary/$wordId': typeof AuthenticatedVocabularyWordIdRoute
  '/vocabulary/flashcards': typeof AuthenticatedVocabularyFlashcardsRoute
  '/vocabulary': typeof AuthenticatedVocabularyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/learn': typeof LearnRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/achievements': typeof AuthenticatedAchievementsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/_authenticated/vocabulary': typeof AuthenticatedVocabularyRouteWithChildren
  '/_authenticated/lesson/$lessonId': typeof AuthenticatedLessonLessonIdRoute
  '/_authenticated/vocabulary/$wordId': typeof AuthenticatedVocabularyWordIdRoute
  '/_authenticated/vocabulary/flashcards': typeof AuthenticatedVocabularyFlashcardsRoute
  '/_authenticated/vocabulary/': typeof AuthenticatedVocabularyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/learn'
    | '/reset-password'
    | '/sitemap.xml'
    | '/achievements'
    | '/admin'
    | '/dashboard'
    | '/leaderboard'
    | '/vocabulary'
    | '/lesson/$lessonId'
    | '/vocabulary/$wordId'
    | '/vocabulary/flashcards'
    | '/vocabulary/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/learn'
    | '/reset-password'
    | '/sitemap.xml'
    | '/achievements'
    | '/admin'
    | '/dashboard'
    | '/leaderboard'
    | '/lesson/$lessonId'
    | '/vocabulary/$wordId'
    | '/vocabulary/flashcards'
    | '/vocabulary'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/learn'
    | '/reset-password'
    | '/sitemap.xml'
    | '/_authenticated/achievements'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/leaderboard'
    | '/_authenticated/vocabulary'
    | '/_authenticated/lesson/$lessonId'
    | '/_authenticated/vocabulary/$wordId'
    | '/_authenticated/vocabulary/flashcards'
    | '/_authenticated/vocabulary/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  LearnRoute: typeof LearnRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/vocabulary': {
      id: '/_authenticated/vocabulary'
      path: '/vocabulary'
      fullPath: '/vocabulary'
      preLoaderRoute: typeof AuthenticatedVocabularyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leaderboard': {
      id: '/_authenticated/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AuthenticatedLeaderboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/achievements': {
      id: '/_authenticated/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AuthenticatedAchievementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vocabulary/': {
      id: '/_authenticated/vocabulary/'
      path: '/'
      fullPath: '/vocabulary/'
      preLoaderRoute: typeof AuthenticatedVocabularyIndexRouteImport
      parentRoute: typeof AuthenticatedVocabularyRoute
    }
    '/_authenticated/vocabulary/flashcards': {
      id: '/_authenticated/vocabulary/flashcards'
      path: '/flashcards'
      fullPath: '/vocabulary/flashcards'
      preLoaderRoute: typeof AuthenticatedVocabularyFlashcardsRouteImport
      parentRoute: typeof AuthenticatedVocabularyRoute
    }
    '/_authenticated/vocabulary/$wordId': {
      id: '/_authenticated/vocabulary/$wordId'
      path: '/$wordId'
      fullPath: '/vocabulary/$wordId'
      preLoaderRoute: typeof AuthenticatedVocabularyWordIdRouteImport
      parentRoute: typeof AuthenticatedVocabularyRoute
    }
    '/_authenticated/lesson/$lessonId': {
      id: '/_authenticated/lesson/$lessonId'
      path: '/lesson/$lessonId'
      fullPath: '/lesson/$lessonId'
      preLoaderRoute: typeof AuthenticatedLessonLessonIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedVocabularyRouteChildren {
  AuthenticatedVocabularyWordIdRoute: typeof AuthenticatedVocabularyWordIdRoute
  AuthenticatedVocabularyFlashcardsRoute: typeof AuthenticatedVocabularyFlashcardsRoute
  AuthenticatedVocabularyIndexRoute: typeof AuthenticatedVocabularyIndexRoute
}

const AuthenticatedVocabularyRouteChildren: AuthenticatedVocabularyRouteChildren =
  {
    AuthenticatedVocabularyWordIdRoute: AuthenticatedVocabularyWordIdRoute,
    AuthenticatedVocabularyFlashcardsRoute:
      AuthenticatedVocabularyFlashcardsRoute,
    AuthenticatedVocabularyIndexRoute: AuthenticatedVocabularyIndexRoute,
  }

const AuthenticatedVocabularyRouteWithChildren =
  AuthenticatedVocabularyRoute._addFileChildren(
    AuthenticatedVocabularyRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAchievementsRoute: typeof AuthenticatedAchievementsRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedLeaderboardRoute: typeof AuthenticatedLeaderboardRoute
  AuthenticatedVocabularyRoute: typeof AuthenticatedVocabularyRouteWithChildren
  AuthenticatedLessonLessonIdRoute: typeof AuthenticatedLessonLessonIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAchievementsRoute: AuthenticatedAchievementsRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedLeaderboardRoute: AuthenticatedLeaderboardRoute,
  AuthenticatedVocabularyRoute: AuthenticatedVocabularyRouteWithChildren,
  AuthenticatedLessonLessonIdRoute: AuthenticatedLessonLessonIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  LearnRoute: LearnRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
